### ISSUE TITLE
Undo on save

### ISSUE THREAD

**Issue by konradmietelski** [pfefferle/atom-php-cs-fixer#20] opened 2015-11-24 14:00 UTC
When I'm trying to save edited *.php file some strange actions are occurring.
It's looks like atom on ctrl-s is doing undo, and then it performs php-cs-fixer:fix.
Code is fixed of course, but I have to manualy do ctrl-z and ctrl-s again to save. Only then my changes are persistent.
When performing saving for the second time everything is fine.

**Comment by pfefferle** [comment] 2015-12-10 09:36
Oh, OK... This is indeed a strange behaviour! I will habe a look.

**Comment by pfefferle** [comment] 2016-01-06 20:13
Sorry, I can't reproduce this behavior.

Can you provide me some more informations, like your operating system, php-cd-fixer version, ...

**Comment by konradmietelski** [comment] 2016-01-13 16:20
Just update everything, error is still occurring.

My system configuration:
Arch Linux, Kernel v4.3.3-2-ARCH
DE: Lxqt v0.10.0
[PHP](https://www.archlinux.org/packages/extra/x86_64/php/) v7.0.2
[php-cs-fixer](https://aur.archlinux.org/packages/php-cs-fixer/) v1.11-2
Atom (current stable) v1.3.3

UPDATE: I've figure it out, that error is occurring only when "Execute on save" is checked. When I perform fixing on my own (with a shortcut) everything is just fine. 

UPDATE2: Package [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/) hit v1.4.0 yesterday. Unfortunately bug is still occurring.

**Comment by pfefferle** [comment] 2016-10-18 20:27
still, I can't reproduce it... is it still a problem?

**Comment by konradmietelski** [comment] 2016-10-19 06:09
I believe not. I can't reproduce this one as well on any of my pc's.

2016-10-18 22:27 GMT+02:00 Matthias Pfefferle notifications@github.com:

**Comment by pfefferle** [comment] 2016-10-19 08:20
@broiniac thanks for checking... then I will close this for now... please re-open if someone still has a problem.

**Closed as completed by pfefferle** 2016-10-19 08:20 UTC
