### ISSUE TITLE
This was abandoned?

### ISSUE THREAD

**Issue by hotwer** [pfefferle/atom-php-cs-fixer#38] opened 2016-10-18 01:31 UTC
I had an issue that was giving me an error that it coulnd't find the php-cs-fixer (on windows), and what I've changed is that is now calls the executable path directly, instead of `php @executablePath`.

You intend to keep developing this plug-in? Or can I fork and add my fixes?

Sorry for any problem I'm giving, I just wanted to keep this project on going as the CS Fixer is still on going as well.

**Comment by pfefferle** [comment] 2016-10-18 06:40
No, it is not abandoned, but I have not much time atm. If you can make a pull request with your changes, I would like to merge it...

**Comment by hotwer** [comment] 2016-10-18 17:12
I sure did the fix for myself, but I'm not actually sure if this fix would have much impact on linux users, as I develop on Windows.
Actually, the plugin itself know doesnt needs the php call, just the command itself, can you assure me that it's now working the same way as the linux? Just to know if I will need to add any test to check wheter we are on unix or windows env.

**Comment by pfefferle** [comment] 2016-10-18 19:18
the problem is, that I added this feature because of windows...

**Comment by pfefferle** [comment] 2016-10-18 19:19
have you tried to use the full path to both, the php executable and the fixer executable?

**Comment by hotwer** [comment] 2016-10-18 19:47
Yes I did, actually what I've tested is that calling like `php path/to/php-cs-fixer` no longer works on windows. To get it to work, I needed to call it alone like just `path/to/php-cs-fixer` instead, without the PHP in front. What I'm asking is that this behaviour is only working for windows or in both it and unix OS based are working this way.

**Comment by pfefferle** [comment] 2016-10-18 19:50
have you tried it with `path/to/php path/to/php-cs-fixer`?

**Comment by hotwer** [comment] 2016-10-18 19:52
Yes, it no longer works this way, I think it's because the new .bat file has the php paremeter in it, so when you call it `php path/to/php-cs-fixer` actually what it does is `php php path/to/php-cs-fixer`

**Comment by pfefferle** [comment] 2016-10-18 20:18
I can not recheck this... can you confirm this behavior @mappedinn or @Dgame?

**Comment by Dgame** [comment] 2016-10-18 20:21
I'm no longer using Atom, sorry.

**Comment by hotwer** [comment] 2016-10-20 14:02
I was just waiting for any answer... So, can I develop the fix?

**Comment by pfefferle** [comment] 2016-10-20 14:17
You can, but I would not recommend removing the php exe completely... perhaps a "setting" to use php or composer directly...

**Comment by hotwer** [comment] 2016-10-20 14:18
that was what i was looking for, an option to be able to call it directly, ok, I will pull request soon as I finished

**Comment by pfefferle** [comment] 2016-10-20 14:20
nice, thanks :)

**Comment by pfefferle** [comment] 2016-12-21 20:39
@hotwer are you still working on that?

**Comment by hotwer** [comment] 2016-12-22 13:37
@pfefferle Sorry, recently I've been working with VS Code, so, sorry, I only did the fix for myself, but didn't have time to go any further. Sorry about that.

**Comment by pfefferle** [comment] 2016-12-22 13:49
no problem, but then I will close this issue for now.

**Closed as completed** 2016-12-22 13:49 UTC
